# Day 9 — Mirage Maintenance

In [158]:
import numpy as np
import pandas as pd

Parse input:

In [159]:
with open(file='day_09_input.txt') as file:
    op = [np.array(line.split(' ')).astype(int) for line in file.read().split('\n')]  # Oasis report

In [160]:
op[:5]

[array([     18,      34,      62,     104,     162,     241,     354,
            541,     935,    1948,    4716,   12044,   30251,   72571,
         165186,  357653,  740584, 1475142, 2841482, 5317016, 9700712]),
 array([     -1,       9,      31,      63,     102,     139,     150,
             87,    -129,    -609,   -1472,   -2740,   -4028,   -3797,
           2219,   24016,   82639,  219061,  508309, 1081061, 2155578]),
 array([     -5,     -12,     -21,     -31,     -28,      39,     297,
           1010,    2680,    6225,   13298,   26846,   52051,   97846,
         179258,  320897,  561985,  963402, 1617317, 2660071, 4289086]),
 array([      16,       31,       55,       93,      166,      327,
             690,     1491,     3227,     6970,    15040,    32365,
           69094,   145421,   300225,   606225,  1196290,  2309185,
         4370163,  8136063, 14963082]),
 array([ 18,  23,  28,  33,  38,  43,  48,  53,  58,  63,  68,  73,  78,
         83,  88,  93,  98, 103, 108, 

### Part 01 / Part 02

In [164]:
def extrapolated_total(hist: list) -> int:
    """
    Predict future values in history and return the sum of those values.
    """
    total_hist = 0
    
    for i in range(len(hist)):
        placeholders = np.array([])  # Placeholder values for current hist
        diff = np.diff(hist[i])

        while True:
            # Append last number in diff
            placeholders = np.append(placeholders, diff[-1]).astype(int)

            if np.all(diff == 0):
                break
            else:
                diff = np.diff(diff)

        # Get the next value in current hist
        next_val = hist[i][-1] + placeholders[-1]
        # All all values to total_hist
        total_hist += placeholders.sum() + next_val
    
    return total_hist

Analyze your OASIS report and extrapolate the next value for each history. What is the sum of these extrapolated values?

In [162]:
# Part 01
extrapolated_total(op)

1731106378

In [163]:
# Part 02
extrapolated_total([hist[::-1] for hist in op])

1087